"""LLM extraction model — fields generated by the LLM via outlines-cascade.

This file is configuration: edit it to change what the LLM extracts.
The LLM sees ONLY these fields. Link, date, publisher, and country are
copied verbatim from the raw feed AFTER generation to prevent hallucination
(country is derived deterministically from the publisher slug).

The web UI auto-generates filter controls from the Literal types here
(list[Literal[...]] fields become multi-select tag filters).
"""

from typing import Literal

from pydantic import BaseModel, Field


class LLMExtraction(BaseModel):
    """Structured output generated by the LLM from press release content.

    Do NOT add url/date/publisher fields here — they are auto-populated
    from the raw feed in ProcessedRelease.
    """

    topics: list[Literal[
        "Consumer prices",
        "Producer prices",
        "Import prices",
        "Export prices",
        "GDP",
        "Industrial production",
        "Services production",
        "International trade",
        "Labour market",
        "Public finance",
        "Retail trade",
        "Construction",
        "Business surveys",
        "Other economic topics",
        "Non-economic topics",
    ]] = Field(
        min_length=1,
        description=(
            "All topics the press release covers — topics are tags, not mutually "
            "exclusive categories. Select every applicable topic (typically 1–3, "
            "ordered by relevance)."
        ),
    )

    sentiment: Literal[
        "positive",
        "negative",
        "neutral",
    ] = Field(description="Economic sentiment conveyed by the data")

    title_en: str = Field(
        description=(
            "English translation of the original press release title. "
            "Keep official statistical terminology. If the title is already "
            "in English, reproduce it verbatim."
        )
    )

    summary_en: str = Field(
        description="Concise English summary of the press release (max 150 words)"
    )

    key_figures: str = Field(
        description=(
            "Key numerical figures mentioned: rates, percentages, index values, "
            "growth rates. Semi-colon-separated. (max 100 characters)"
        )
    )
